description:>
  The only difference between RC and Replicasets is that Replicaset takes into account already running pods.
  

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    type: web-server
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: web-server
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
     type: web-server
