description:>
  task4: creating pod to use volume for storage. 
  emptyDir volume: emptydir is first created as soon as the pod gets assigned to a node and it exists as long as the 
  pods keeps running on the node. Initially it is empty, the contaiers in the pod can write into this directory and this is 
  available as long as pod is available irrespective of containers.
  
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: nginx-path
      mountPath: /data/storage
    volumes:
    - name: nginx-path
      emptyDir: {}                        #this empty dir willbe untill pod is deleted, events if container restarts the data will still be available.
 
 

---
#using host directory. i.r directly mounting on to node directory. 
#even if pod os deleted the data wills till be available.
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /opt/
    volumes:
    - name: nginx-data
      hostPath: 
       path: /data/
       type: Directory
    

      
      
